version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.11.0-dysprosium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.11.0-dysprosium
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm      
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.11.0-dysprosium
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm      
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444